/*
 * Copyright (c) 2022 vitasystems GmbH and Hannover Medical School.
 *
 * This file is part of project EHRbase
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.ehrbase.jooq.pg.tables;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.ehrbase.jooq.pg.Ehr;
import org.ehrbase.jooq.pg.Keys;
import org.ehrbase.jooq.pg.enums.ContributionChangeType;
import org.ehrbase.jooq.pg.tables.records.AuditDetailsRecord;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class AuditDetails extends TableImpl<AuditDetailsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>ehr.audit_details</code>
     */
    public static final AuditDetails AUDIT_DETAILS = new AuditDetails();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuditDetailsRecord> getRecordType() {
        return AuditDetailsRecord.class;
    }

    /**
     * The column <code>ehr.audit_details.id</code>.
     */
    public final TableField<AuditDetailsRecord, UUID> ID = createField(
            DSL.name("id"),
            SQLDataType.UUID.nullable(false).defaultValue(DSL.field("uuid_generate_v4()", SQLDataType.UUID)),
            this,
            "");

    /**
     * The column <code>ehr.audit_details.system_id</code>.
     */
    public final TableField<AuditDetailsRecord, UUID> SYSTEM_ID =
            createField(DSL.name("system_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.committer</code>.
     */
    public final TableField<AuditDetailsRecord, UUID> COMMITTER =
            createField(DSL.name("committer"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.time_committed</code>.
     */
    public final TableField<AuditDetailsRecord, Timestamp> TIME_COMMITTED = createField(
            DSL.name("time_committed"),
            SQLDataType.TIMESTAMP(6).defaultValue(DSL.field("now()", SQLDataType.TIMESTAMP)),
            this,
            "");

    /**
     * The column <code>ehr.audit_details.time_committed_tzid</code>.
     */
    public final TableField<AuditDetailsRecord, String> TIME_COMMITTED_TZID =
            createField(DSL.name("time_committed_tzid"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>ehr.audit_details.change_type</code>.
     */
    public final TableField<AuditDetailsRecord, ContributionChangeType> CHANGE_TYPE = createField(
            DSL.name("change_type"),
            SQLDataType.VARCHAR.nullable(false).asEnumDataType(org.ehrbase.jooq.pg.enums.ContributionChangeType.class),
            this,
            "");

    /**
     * The column <code>ehr.audit_details.description</code>.
     */
    public final TableField<AuditDetailsRecord, String> DESCRIPTION =
            createField(DSL.name("description"), SQLDataType.CLOB, this, "");

    private AuditDetails(Name alias, Table<AuditDetailsRecord> aliased) {
        this(alias, aliased, null);
    }

    private AuditDetails(Name alias, Table<AuditDetailsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    /**
     * Create an aliased <code>ehr.audit_details</code> table reference
     */
    public AuditDetails(String alias) {
        this(DSL.name(alias), AUDIT_DETAILS);
    }

    /**
     * Create an aliased <code>ehr.audit_details</code> table reference
     */
    public AuditDetails(Name alias) {
        this(alias, AUDIT_DETAILS);
    }

    /**
     * Create a <code>ehr.audit_details</code> table reference
     */
    public AuditDetails() {
        this(DSL.name("audit_details"), null);
    }

    public <O extends Record> AuditDetails(Table<O> child, ForeignKey<O, AuditDetailsRecord> key) {
        super(child, key, AUDIT_DETAILS);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Ehr.EHR;
    }

    @Override
    public UniqueKey<AuditDetailsRecord> getPrimaryKey() {
        return Keys.AUDIT_DETAILS_PKEY;
    }

    @Override
    public List<ForeignKey<AuditDetailsRecord, ?>> getReferences() {
        return Arrays.asList(
                Keys.AUDIT_DETAILS__AUDIT_DETAILS_SYSTEM_ID_FKEY, Keys.AUDIT_DETAILS__AUDIT_DETAILS_COMMITTER_FKEY);
    }

    private transient System _system;
    private transient PartyIdentified _partyIdentified;

    /**
     * Get the implicit join path to the <code>ehr.system</code> table.
     */
    public System system() {
        if (_system == null) _system = new System(this, Keys.AUDIT_DETAILS__AUDIT_DETAILS_SYSTEM_ID_FKEY);

        return _system;
    }

    /**
     * Get the implicit join path to the <code>ehr.party_identified</code>
     * table.
     */
    public PartyIdentified partyIdentified() {
        if (_partyIdentified == null)
            _partyIdentified = new PartyIdentified(this, Keys.AUDIT_DETAILS__AUDIT_DETAILS_COMMITTER_FKEY);

        return _partyIdentified;
    }

    @Override
    public AuditDetails as(String alias) {
        return new AuditDetails(DSL.name(alias), this);
    }

    @Override
    public AuditDetails as(Name alias) {
        return new AuditDetails(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDetails rename(String name) {
        return new AuditDetails(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AuditDetails rename(Name name) {
        return new AuditDetails(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, UUID, UUID, Timestamp, String, ContributionChangeType, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
