apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcp-backend          
  target:                                                             
    name: {{ .Values.secrets.name }}  # name of the k8s Secret to be created
  data:
  {{ range .Values.secrets.items }}
  - secretKey: {{ .target }} 
    remoteRef:            
      key: {{ .gcpRemoteKey }}        # name of the GCPSM secret key
  {{ end }}