apiVersion: v1
kind: Service
metadata:
  name: {{ include "app.fullname" . }}
  annotations:
    cloud.google.com/app-protocols: '{"http":"HTTP"}'
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
