# Copyright (c) 2019 Vitasystems GmbH and Hannover Medical School.
#
# This file is part of Project EHRbase
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    hikari:
      maximum-pool-size: 50
      max-lifetime: 1800000
      minimum-idle: 10
  flyway:
    schemas: ehr
    user: ${DB_USER_ADMIN}
    password: ${DB_PASS_ADMIN}
security:
  authType: NONE

server:
  port: 8080
  # Optional custom server nodename
  # nodename: 'local.test.org'
  servlet:
    context-path: /ehrbase

  aqlConfig:
    # if true, WHERE clause is using jsquery, false uses SQL only
    useJsQuery: false
    # ignore unbounded item in path starting with one of
    ignoreIterativeNodeList: 'events,activities,content'
    # how many embedded jsonb_array_elements(..) are acceptable? Recommended == 1
    iterationScanDepth: 1
    
admin-api:
  active: false
  allowDeleteAll: false
  context-path: /rest/admin
