
validation:
  external-terminology:
    authenticate: false

spring:
  security:
    oauth2:
      client:
        registration:
          custom:
            client-id: HIP-CDR-EHRbase-Service
            client-secret: e3e25eafef04f27c7d75d672f24f8bcf281d111fb48a3a4c4e601054b2094394
            authorization-grant-type: client_credentials
        provider:
          custom:
            token-uri: http://localhost:8081/auth/realms/myTestRealm-c76fe4ff-28a4-4b24-9550-d34a324a836d/protocol/openid-connect/token