/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.routines;


import java.util.UUID;

import org.ehrbase.jooq.pg.Ehr;
import org.jooq.Field;
import org.jooq.JSON;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class JsCanonicalParticipations extends AbstractRoutine<JSON> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>ehr.js_canonical_participations.RETURN_VALUE</code>.
     */
    public static final Parameter<JSON> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.JSON, false, false);

    /**
     * The parameter <code>ehr.js_canonical_participations.context_id</code>.
     */
    public static final Parameter<UUID> CONTEXT_ID = Internal.createParameter("context_id", SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public JsCanonicalParticipations() {
        super("js_canonical_participations", Ehr.EHR, SQLDataType.JSON);

        setReturnParameter(RETURN_VALUE);
        addInParameter(CONTEXT_ID);
    }

    /**
     * Set the <code>context_id</code> parameter IN value to the routine
     */
    public void setContextId(UUID value) {
        setValue(CONTEXT_ID, value);
    }

    /**
     * Set the <code>context_id</code> parameter to the function to be used with
     * a {@link org.jooq.Select} statement
     */
    public void setContextId(Field<UUID> field) {
        setField(CONTEXT_ID, field);
    }
}
