//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CodeSystemHierarchyMeaning-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CodeSystemHierarchyMeaning-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="grouped-by"/>
 *     &lt;enumeration value="is-a"/>
 *     &lt;enumeration value="part-of"/>
 *     &lt;enumeration value="classified-with"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CodeSystemHierarchyMeaning-list")
@XmlEnum
public enum CodeSystemHierarchyMeaningList {


    /**
     * Grouped By
     * 
     */
    @XmlEnumValue("grouped-by")
    GROUPED_BY("grouped-by"),

    /**
     * Is-A
     * 
     */
    @XmlEnumValue("is-a")
    IS_A("is-a"),

    /**
     * Part Of
     * 
     */
    @XmlEnumValue("part-of")
    PART_OF("part-of"),

    /**
     * Classified With
     * 
     */
    @XmlEnumValue("classified-with")
    CLASSIFIED_WITH("classified-with");
    private final java.lang.String value;

    CodeSystemHierarchyMeaningList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static CodeSystemHierarchyMeaningList fromValue(java.lang.String v) {
        for (CodeSystemHierarchyMeaningList c: CodeSystemHierarchyMeaningList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
