//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DeviceMetricCalibrationState-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DeviceMetricCalibrationState-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="not-calibrated"/>
 *     &lt;enumeration value="calibration-required"/>
 *     &lt;enumeration value="calibrated"/>
 *     &lt;enumeration value="unspecified"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DeviceMetricCalibrationState-list")
@XmlEnum
public enum DeviceMetricCalibrationStateList {


    /**
     * Not Calibrated
     * 
     */
    @XmlEnumValue("not-calibrated")
    NOT_CALIBRATED("not-calibrated"),

    /**
     * Calibration Required
     * 
     */
    @XmlEnumValue("calibration-required")
    CALIBRATION_REQUIRED("calibration-required"),

    /**
     * Calibrated
     * 
     */
    @XmlEnumValue("calibrated")
    CALIBRATED("calibrated"),

    /**
     * Unspecified
     * 
     */
    @XmlEnumValue("unspecified")
    UNSPECIFIED("unspecified");
    private final java.lang.String value;

    DeviceMetricCalibrationStateList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static DeviceMetricCalibrationStateList fromValue(java.lang.String v) {
        for (DeviceMetricCalibrationStateList c: DeviceMetricCalibrationStateList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
