//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The characteristics, operational status and capabilities of a medical-related component of a medical device.
 * 
 * <p>Java class for DeviceDefinition.UdiDeviceIdentifier complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DeviceDefinition.UdiDeviceIdentifier">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="deviceIdentifier" type="{http://hl7.org/fhir}string"/>
 *         &lt;element name="issuer" type="{http://hl7.org/fhir}uri"/>
 *         &lt;element name="jurisdiction" type="{http://hl7.org/fhir}uri"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceDefinition.UdiDeviceIdentifier", propOrder = {
    "deviceIdentifier",
    "issuer",
    "jurisdiction"
})
public class DeviceDefinitionUdiDeviceIdentifier
    extends BackboneElement
{

    @XmlElement(required = true)
    protected String deviceIdentifier;
    @XmlElement(required = true)
    protected Uri issuer;
    @XmlElement(required = true)
    protected Uri jurisdiction;

    /**
     * Gets the value of the deviceIdentifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceIdentifier() {
        return deviceIdentifier;
    }

    /**
     * Sets the value of the deviceIdentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceIdentifier(String value) {
        this.deviceIdentifier = value;
    }

    /**
     * Gets the value of the issuer property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getIssuer() {
        return issuer;
    }

    /**
     * Sets the value of the issuer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setIssuer(Uri value) {
        this.issuer = value;
    }

    /**
     * Gets the value of the jurisdiction property.
     * 
     * @return
     *     possible object is
     *     {@link Uri }
     *     
     */
    public Uri getJurisdiction() {
        return jurisdiction;
    }

    /**
     * Sets the value of the jurisdiction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Uri }
     *     
     */
    public void setJurisdiction(Uri value) {
        this.jurisdiction = value;
    }

}
