//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * Detailed definition of a medicinal product, typically for uses other than direct patient care (e.g. regulatory use).
 * 
 * <p>Java class for MedicinalProduct.ManufacturingBusinessOperation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MedicinalProduct.ManufacturingBusinessOperation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}BackboneElement">
 *       &lt;sequence>
 *         &lt;element name="operationType" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="authorisationReferenceNumber" type="{http://hl7.org/fhir}Identifier" minOccurs="0"/>
 *         &lt;element name="effectiveDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="confidentialityIndicator" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="manufacturer" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="regulator" type="{http://hl7.org/fhir}Reference" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MedicinalProduct.ManufacturingBusinessOperation", propOrder = {
    "operationType",
    "authorisationReferenceNumber",
    "effectiveDate",
    "confidentialityIndicator",
    "manufacturer",
    "regulator"
})
public class MedicinalProductManufacturingBusinessOperation
    extends BackboneElement
{

    protected CodeableConcept operationType;
    protected Identifier authorisationReferenceNumber;
    protected DateTime effectiveDate;
    protected CodeableConcept confidentialityIndicator;
    protected List<Reference> manufacturer;
    protected Reference regulator;

    /**
     * Gets the value of the operationType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getOperationType() {
        return operationType;
    }

    /**
     * Sets the value of the operationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setOperationType(CodeableConcept value) {
        this.operationType = value;
    }

    /**
     * Gets the value of the authorisationReferenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Identifier }
     *     
     */
    public Identifier getAuthorisationReferenceNumber() {
        return authorisationReferenceNumber;
    }

    /**
     * Sets the value of the authorisationReferenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Identifier }
     *     
     */
    public void setAuthorisationReferenceNumber(Identifier value) {
        this.authorisationReferenceNumber = value;
    }

    /**
     * Gets the value of the effectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getEffectiveDate() {
        return effectiveDate;
    }

    /**
     * Sets the value of the effectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setEffectiveDate(DateTime value) {
        this.effectiveDate = value;
    }

    /**
     * Gets the value of the confidentialityIndicator property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getConfidentialityIndicator() {
        return confidentialityIndicator;
    }

    /**
     * Sets the value of the confidentialityIndicator property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setConfidentialityIndicator(CodeableConcept value) {
        this.confidentialityIndicator = value;
    }

    /**
     * Gets the value of the manufacturer property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacturer property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacturer().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getManufacturer() {
        if (manufacturer == null) {
            manufacturer = new ArrayList<Reference>();
        }
        return this.manufacturer;
    }

    /**
     * Gets the value of the regulator property.
     * 
     * @return
     *     possible object is
     *     {@link Reference }
     *     
     */
    public Reference getRegulator() {
        return regulator;
    }

    /**
     * Sets the value of the regulator property.
     * 
     * @param value
     *     allowed object is
     *     {@link Reference }
     *     
     */
    public void setRegulator(Reference value) {
        this.regulator = value;
    }

}
