//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StructureMapGroupTypeMode-list.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="StructureMapGroupTypeMode-list">
 *   &lt;restriction base="{http://hl7.org/fhir}code-primitive">
 *     &lt;enumeration value="none"/>
 *     &lt;enumeration value="types"/>
 *     &lt;enumeration value="type-and-types"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "StructureMapGroupTypeMode-list")
@XmlEnum
public enum StructureMapGroupTypeModeList {


    /**
     * Not a Default
     * 
     */
    @XmlEnumValue("none")
    NONE("none"),

    /**
     * Default for Type Combination
     * 
     */
    @XmlEnumValue("types")
    TYPES("types"),

    /**
     * Default for type + combination
     * 
     */
    @XmlEnumValue("type-and-types")
    TYPE_AND_TYPES("type-and-types");
    private final java.lang.String value;

    StructureMapGroupTypeModeList(java.lang.String v) {
        value = v;
    }

    public java.lang.String value() {
        return value;
    }

    public static StructureMapGroupTypeModeList fromValue(java.lang.String v) {
        for (StructureMapGroupTypeModeList c: StructureMapGroupTypeModeList.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
