//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for SubstanceReferenceInformation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SubstanceReferenceInformation">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="comment" type="{http://hl7.org/fhir}string" minOccurs="0"/>
 *         &lt;element name="gene" type="{http://hl7.org/fhir}SubstanceReferenceInformation.Gene" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="geneElement" type="{http://hl7.org/fhir}SubstanceReferenceInformation.GeneElement" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="classification" type="{http://hl7.org/fhir}SubstanceReferenceInformation.Classification" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="target" type="{http://hl7.org/fhir}SubstanceReferenceInformation.Target" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubstanceReferenceInformation", propOrder = {
    "comment",
    "gene",
    "geneElement",
    "classification",
    "target"
})
public class SubstanceReferenceInformation
    extends DomainResource
{

    protected String comment;
    protected List<SubstanceReferenceInformationGene> gene;
    protected List<SubstanceReferenceInformationGeneElement> geneElement;
    protected List<SubstanceReferenceInformationClassification> classification;
    protected List<SubstanceReferenceInformationTarget> target;

    /**
     * Gets the value of the comment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getComment() {
        return comment;
    }

    /**
     * Sets the value of the comment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setComment(String value) {
        this.comment = value;
    }

    /**
     * Gets the value of the gene property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the gene property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGene().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceReferenceInformationGene }
     * 
     * 
     */
    public List<SubstanceReferenceInformationGene> getGene() {
        if (gene == null) {
            gene = new ArrayList<SubstanceReferenceInformationGene>();
        }
        return this.gene;
    }

    /**
     * Gets the value of the geneElement property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the geneElement property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneElement().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceReferenceInformationGeneElement }
     * 
     * 
     */
    public List<SubstanceReferenceInformationGeneElement> getGeneElement() {
        if (geneElement == null) {
            geneElement = new ArrayList<SubstanceReferenceInformationGeneElement>();
        }
        return this.geneElement;
    }

    /**
     * Gets the value of the classification property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classification property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassification().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceReferenceInformationClassification }
     * 
     * 
     */
    public List<SubstanceReferenceInformationClassification> getClassification() {
        if (classification == null) {
            classification = new ArrayList<SubstanceReferenceInformationClassification>();
        }
        return this.classification;
    }

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceReferenceInformationTarget }
     * 
     * 
     */
    public List<SubstanceReferenceInformationTarget> getTarget() {
        if (target == null) {
            target = new ArrayList<SubstanceReferenceInformationTarget>();
        }
        return this.target;
    }

}
