//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.26 at 01:33:12 PM CET 
//


package org.ehrbase.aql.compiler.tsclient.fhir.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * If the element is present, it must have either a @value, an @id, or extensions
 * 
 * <p>Java class for VerificationResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerificationResult">
 *   &lt;complexContent>
 *     &lt;extension base="{http://hl7.org/fhir}DomainResource">
 *       &lt;sequence>
 *         &lt;element name="target" type="{http://hl7.org/fhir}Reference" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="targetLocation" type="{http://hl7.org/fhir}string" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="need" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="status" type="{http://hl7.org/fhir}status"/>
 *         &lt;element name="statusDate" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="validationType" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="validationProcess" type="{http://hl7.org/fhir}CodeableConcept" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="frequency" type="{http://hl7.org/fhir}Timing" minOccurs="0"/>
 *         &lt;element name="lastPerformed" type="{http://hl7.org/fhir}dateTime" minOccurs="0"/>
 *         &lt;element name="nextScheduled" type="{http://hl7.org/fhir}date" minOccurs="0"/>
 *         &lt;element name="failureAction" type="{http://hl7.org/fhir}CodeableConcept" minOccurs="0"/>
 *         &lt;element name="primarySource" type="{http://hl7.org/fhir}VerificationResult.PrimarySource" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="attestation" type="{http://hl7.org/fhir}VerificationResult.Attestation" minOccurs="0"/>
 *         &lt;element name="validator" type="{http://hl7.org/fhir}VerificationResult.Validator" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerificationResult", propOrder = {
    "target",
    "targetLocation",
    "need",
    "status",
    "statusDate",
    "validationType",
    "validationProcess",
    "frequency",
    "lastPerformed",
    "nextScheduled",
    "failureAction",
    "primarySource",
    "attestation",
    "validator"
})
public class VerificationResult
    extends DomainResource
{

    protected List<Reference> target;
    protected List<String> targetLocation;
    protected CodeableConcept need;
    @XmlElement(required = true)
    protected Status status;
    protected DateTime statusDate;
    protected CodeableConcept validationType;
    protected List<CodeableConcept> validationProcess;
    protected Timing frequency;
    protected DateTime lastPerformed;
    protected Date nextScheduled;
    protected CodeableConcept failureAction;
    protected List<VerificationResultPrimarySource> primarySource;
    protected VerificationResultAttestation attestation;
    protected List<VerificationResultValidator> validator;

    /**
     * Gets the value of the target property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the target property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTarget().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Reference }
     * 
     * 
     */
    public List<Reference> getTarget() {
        if (target == null) {
            target = new ArrayList<Reference>();
        }
        return this.target;
    }

    /**
     * Gets the value of the targetLocation property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the targetLocation property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTargetLocation().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getTargetLocation() {
        if (targetLocation == null) {
            targetLocation = new ArrayList<String>();
        }
        return this.targetLocation;
    }

    /**
     * Gets the value of the need property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getNeed() {
        return need;
    }

    /**
     * Sets the value of the need property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setNeed(CodeableConcept value) {
        this.need = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link Status }
     *     
     */
    public Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link Status }
     *     
     */
    public void setStatus(Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setStatusDate(DateTime value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the validationType property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getValidationType() {
        return validationType;
    }

    /**
     * Sets the value of the validationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setValidationType(CodeableConcept value) {
        this.validationType = value;
    }

    /**
     * Gets the value of the validationProcess property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validationProcess property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidationProcess().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CodeableConcept }
     * 
     * 
     */
    public List<CodeableConcept> getValidationProcess() {
        if (validationProcess == null) {
            validationProcess = new ArrayList<CodeableConcept>();
        }
        return this.validationProcess;
    }

    /**
     * Gets the value of the frequency property.
     * 
     * @return
     *     possible object is
     *     {@link Timing }
     *     
     */
    public Timing getFrequency() {
        return frequency;
    }

    /**
     * Sets the value of the frequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timing }
     *     
     */
    public void setFrequency(Timing value) {
        this.frequency = value;
    }

    /**
     * Gets the value of the lastPerformed property.
     * 
     * @return
     *     possible object is
     *     {@link DateTime }
     *     
     */
    public DateTime getLastPerformed() {
        return lastPerformed;
    }

    /**
     * Sets the value of the lastPerformed property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateTime }
     *     
     */
    public void setLastPerformed(DateTime value) {
        this.lastPerformed = value;
    }

    /**
     * Gets the value of the nextScheduled property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getNextScheduled() {
        return nextScheduled;
    }

    /**
     * Sets the value of the nextScheduled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setNextScheduled(Date value) {
        this.nextScheduled = value;
    }

    /**
     * Gets the value of the failureAction property.
     * 
     * @return
     *     possible object is
     *     {@link CodeableConcept }
     *     
     */
    public CodeableConcept getFailureAction() {
        return failureAction;
    }

    /**
     * Sets the value of the failureAction property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodeableConcept }
     *     
     */
    public void setFailureAction(CodeableConcept value) {
        this.failureAction = value;
    }

    /**
     * Gets the value of the primarySource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the primarySource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPrimarySource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationResultPrimarySource }
     * 
     * 
     */
    public List<VerificationResultPrimarySource> getPrimarySource() {
        if (primarySource == null) {
            primarySource = new ArrayList<VerificationResultPrimarySource>();
        }
        return this.primarySource;
    }

    /**
     * Gets the value of the attestation property.
     * 
     * @return
     *     possible object is
     *     {@link VerificationResultAttestation }
     *     
     */
    public VerificationResultAttestation getAttestation() {
        return attestation;
    }

    /**
     * Sets the value of the attestation property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerificationResultAttestation }
     *     
     */
    public void setAttestation(VerificationResultAttestation value) {
        this.attestation = value;
    }

    /**
     * Gets the value of the validator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VerificationResultValidator }
     * 
     * 
     */
    public List<VerificationResultValidator> getValidator() {
        if (validator == null) {
            validator = new ArrayList<VerificationResultValidator>();
        }
        return this.validator;
    }

}
