/*
 * This file is generated by jOOQ.
 */
package org.ehrbase.jooq.pg.tables.records;


import org.ehrbase.jooq.pg.tables.AdminDeleteStatusHistory;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Row1;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AdminDeleteStatusHistoryRecord extends TableRecordImpl<AdminDeleteStatusHistoryRecord> implements Record1<Integer> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>ehr.admin_delete_status_history.num</code>.
     */
    public void setNum(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ehr.admin_delete_status_history.num</code>.
     */
    public Integer getNum() {
        return (Integer) get(0);
    }

    // -------------------------------------------------------------------------
    // Record1 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row1<Integer> fieldsRow() {
        return (Row1) super.fieldsRow();
    }

    @Override
    public Row1<Integer> valuesRow() {
        return (Row1) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return AdminDeleteStatusHistory.ADMIN_DELETE_STATUS_HISTORY.NUM;
    }

    @Override
    public Integer component1() {
        return getNum();
    }

    @Override
    public Integer value1() {
        return getNum();
    }

    @Override
    public AdminDeleteStatusHistoryRecord value1(Integer value) {
        setNum(value);
        return this;
    }

    @Override
    public AdminDeleteStatusHistoryRecord values(Integer value1) {
        value1(value1);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AdminDeleteStatusHistoryRecord
     */
    public AdminDeleteStatusHistoryRecord() {
        super(AdminDeleteStatusHistory.ADMIN_DELETE_STATUS_HISTORY);
    }

    /**
     * Create a detached, initialised AdminDeleteStatusHistoryRecord
     */
    public AdminDeleteStatusHistoryRecord(Integer num) {
        super(AdminDeleteStatusHistory.ADMIN_DELETE_STATUS_HISTORY);

        setNum(num);
    }
}
