name: 'Preparation'
description: 'Preparete agent before running anything'

inputs:
  google_cred:
    description: 'Google Creds'
    required: true
  gcr_domain:
    description: 'GCR Domain'
    required: true
  gcp_project:
    description: 'GCP Project ID'
    required: true
  gke_cluster:
    description: 'GKE Cluster name'
    required: true
  gcp_region:
    description: 'GCP region name'
    required: true

runs:
  using: "composite"
  steps:

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      with:
        buildkitd-flags: --debug

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ inputs.google_cred }}'

    # Install gcloud, `setup-gcloud` automatically picks up authentication from `auth`.
    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    # Now you can run gcloud commands authenticated as the impersonated service account.
    - id: 'gcloud'
      name: 'gcloud'
      shell: bash
      run: |-
        gcloud auth configure-docker '${{ inputs.gcr_domain }}' --project='${{ inputs.gcp_project }}'
    
    - name: kubectl
      shell: bash
      run: |-
        gcloud container clusters get-credentials '${{ inputs.gke_cluster }}' --project='${{ inputs.gcp_project }}' --region='${{ inputs.gcp_region }}'