name: 'Build and Push'
description: 'Build Docker image and Push to GCR'

inputs:
  gcr_path:
    description: 'gcr Path'
    required: true
  gcr_domain:
    description: 'GCR Domain'
    required: true

outputs:
  image_tag: 
    description: 'Image tag'
    value: ${{ steps.release_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}
  image_address:
    description: 'Image address'
    value: ${{ inputs.gcr_domain }}/${{ inputs.gcr_path }}/${{ github.event.repository.name }}

runs:
  using: "composite"
  steps:

    - name: Get branch name (pull request)
      id: branch_pr
      if: github.event_name == 'pull_request'
      shell: bash
      run: echo "NAME=$(echo ${{github.head_ref}} | tr / -)" >> $GITHUB_OUTPUT
    
    - name: Get branch name (branch)
      id: branch_custom
      if: github.ref != 'refs/heads/main' 
      shell: bash
      run: echo "NAME=$(echo ${{github.ref_name}} | tr / -)" >> $GITHUB_OUTPUT

    # Action Docs - https://github.com/marketplace/actions/git-semantic-version
    - name: Increment Release Image Version
      id: release_bump_version
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: paulhatch/semantic-version@v5.0.3
      with:
        tag_prefix: "v"
        version_format: '${major}.${minor}.${patch}'
        bump_each_commit: true
        search_commit_body: false

    - name: Increment Feature Image Version
      id: feature_bump_version
      if: github.ref != 'refs/heads/main'
      uses: paulhatch/semantic-version@v5.0.3
      with:
        tag_prefix: ""
        version_format: '${major}.${minor}.${patch}-${{ steps.branch_pr.outputs.NAME || steps.branch_custom.outputs.NAME  }}${increment}'

    - name: Build 
      shell: bash
      run: |-
        mvn clean
        mvn compile com.google.cloud.tools:jib-maven-plugin:3.3.1:dockerBuild -Dimage="${{ inputs.gcr_domain }}/${{ inputs.gcr_path }}/${{ github.event.repository.name }}:${{ steps.release_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}"
    
    - name: Push
      shell: bash
      run: |-
        docker push ${{ inputs.gcr_domain }}/${{ inputs.gcr_path }}/${{ github.event.repository.name }}:${{ steps.release_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}

    - name: Image address
      shell: bash
      run: echo "${{ inputs.gcr_domain }}/${{ inputs.gcr_path }}/${{ github.event.repository.name }}:${{ steps.release_bump_version.outputs.version || steps.feature_bump_version.outputs.version }}"
