name: publish maven

on:
  push:
    branches:
      - develop
      - master
    paths-ignore:
      - '.circleci/**'
      - '.docker_scripts/**'
      - '.github/**'
      - 'doc/**'
      - 'tests/**'
      - '**/*.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      ehrbase-db:
        image: ehrbase/ehrbase-postgres:13.4.v2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          EHRBASE_USER_ADMIN: ehrbase
          EHRBASE_PASSWORD_ADMIN: ehrbase
          EHRBASE_USER: ehrbase_restricted
          EHRBASE_PASSWORD: ehrbase_restricted

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify

      - name: Setup Maven Central
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Publish to Maven Central
        run: mvn -B deploy -P release -DskipTests
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
