name: build

on:
  push:
    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    services:
      ehrbase-db:
        image: yugabytedb/yugabyte:2.16.2.0-b41
        ports:
          - 5433:5433
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres


    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: Run Create DB script
        run: psql -h localhost -p 5433 -f base/db-setup/createdb.sql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify
