name: build

on:
  push:
    branches: [ feature/CDR-903_pipeline_different_ehrbase_creds ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    services:
      ehrbase-db:
        image: ehrbase/ehrbase-postgres:13.4.v2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          EHRBASE_USER_ADMIN: ehrbase
          EHRBASE_PASSWORD_ADMIN: ehrbase
          EHRBASE_USER: ehrbase_user_username
          EHRBASE_PASSWORD: ehrbase_user_password

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify
