name: build

on:
  push:
    branches: [ feature/CDR-903_pipeline_different_ehrbase_creds ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]

    services:
      ehrbase-db:
        image: ehrbase/ehrbase-postgres:13.4.v2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          EHRBASE_USER_ADMIN: ehrbase
          EHRBASE_PASSWORD_ADMIN: ehrbase
          EHRBASE_USER: ehrbase_restricted
          EHRBASE_PASSWORD: ehrbase_restricted

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify
        
      - name: Run ehrbase
        run: |
          java -jar application/target/application-0.28.0-SNAPSHOT.jar --server.nodename=local.ehrbase.org >/var/tmp/log.txt &
          sleep 30
          cat /var/tmp/log.txt
          
      - name: Checkout robot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ehrbase/integration-tests
          ref: main
          
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install -r tests/requirements.txt
        
      - name: Run robot
        run: |
          cd tests
          robot -v nodocker \
                -v NODENAME:local.ehrbase.org \
                --console dotted \
                --flattenkeywords for \
                --flattenkeywords foritem \
                --flattenkeywords name:_resources.* \
                -d results \
                --noncritical not-ready -L TRACE \
                robot/SANITY_TESTS >/var/tmp/log.txt
                
      - name: Cleanup Robot results folder
        if: always()
        run: |
          rm -vf /home/runner/work/ehrbase/ehrbase/tests/results/*.xml
          
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-result
          path: /home/runner/work/ehrbase/ehrbase/tests/results/

      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: /var/tmp/log.txt