name: build

on:
  push:
    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]



    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Create DB script
        run: |
          docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 yugabytedb/yugabyte:2.16.2.0-b41 bin/yugabyted start --daemon=false
          sleep 30
          docker ps
          psql -h localhost -p 5433 -f base/db-setup/createdb.sql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify

      - name: Login to GitLab
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ehrbase/ehrbasemvp:mvp1


      - name: Run ehrbase
        run: |
          java -jar application/target/application-0.26.0-SNAPSHOT.jar --spring.profiles.active=yugabytedb >/var/tmp/log.txt &
          sleep 30
          cat /var/tmp/log.txt

      - name: Checkout robot
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: ehrbase/integration-tests
          ref: feature/new

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: pip install -r tests/requirements.txt

      - name: Run robot
        run: |
          cd tests
          robot -v nodocker  -d results --noncritical not-ready -L TRACE robot/
      - name: Archive code coverage results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: robot-result
          path: /home/runner/work/ehrbase_aql_mvp/ehrbase_aql_mvp/tests/results/
      - name: Archive logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: log
          path: /var/tmp/log.txt