name: build

on:
  push:
    branches: [ develop ]
#  pull_request:
#    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17' ]



    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0



      - name: Run Create DB script
        run: |
          docker run -d --name yugabyte  -p7000:7000 -p9000:9000 -p5433:5433 -p9042:9042 yugabytedb/yugabyte:2.16.2.0-b41 bin/yugabyted start --daemon=false
          sleep 30
          docker ps
          psql -h localhost -p 5433 -f base/db-setup/createdb.sql
        env:
          PGUSER: postgres
          PGPASSWORD: postgres

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B verify

      - name: Run ehrbase
        run: |
          java -jar application/target/application-0.26.0-SNAPSHOT.jar --spring.profiles.active=yugabytedb >log.txt &
          sleep 30
          cat log.txt