name: production-deployment

on: workflow_dispatch

jobs:
  build:
    runs-on: ["elmeas", "Linux"] 
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      
      - name: Preperation
        uses: ./.github/actions/prepare
        with:
          gke_cluster: production-cluster
          gcp_project: production-404312
          gcp_region: europe-west3
          google_cred: ${{ secrets.GOOGLE_CREDENTIALS }}
          gcr_domain: ${{ vars.GCR_DOMAIN }}

      - name: Build and Push
        id: build
        uses: ./.github/actions/build-and-push
        with:
          gcr_domain: ${{ vars.GCR_DOMAIN }}
          gcr_path: adminplane/erhbase

  approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: ProductionApproval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: alirahm2, hojatv, nosovsh, DunnCoding
          minimum-approvals: 1
          issue-title: "Deploying to PROD version ${{ needs.build.outputs.image_tag }}"
          issue-body: "Please approve or deny the deployment for PROD for version ${{ needs.build.outputs.image_tag }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''
          
  deploy:
    runs-on: ["elmeas", "Linux"] 
    needs: [approval, build]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Preperation
      uses: ./.github/actions/prepare
      with:
        gke_cluster: production-cluster
        gcp_project: production-404312
        gcp_region: europe-west3
        google_cred: ${{ secrets.GOOGLE_CREDENTIALS }}
        gcr_domain: ${{ vars.GCR_DOMAIN }}
    
    - name: Deploy
      uses: ./.github/actions/deploy
      with:
        name: ehrbase
        namespace: ehrbase
        environment: production
        image_tag: ${{needs.build.outputs.image_tag}} 
    
