name: Sandbox

on: workflow_dispatch

jobs:
  build:
    runs-on: ["elmeas", "Linux"] 
    outputs:
      image_tag: ${{ steps.build.outputs.image_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      
      - name: Preperation
        uses: ./.github/actions/prepare
        with:
          gke_cluster: sandbox-cluster
          gcp_project: elmeas-sandbox
          gcp_region: europe-west3
          google_cred: ${{ secrets.GOOGLE_CREDENTIALS }}
          gcr_domain: ${{ vars.GCR_DOMAIN }}

      - name: Build and Push
        id: build
        uses: ./.github/actions/build-and-push
        with:
          gcr_domain: ${{ vars.GCR_DOMAIN }}
          gcr_path: adminplane/ehrbase

  check-approvals:
    name: "Approval Request"
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Sandbox Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: alirahm2, hojatv, nosovsh, DunnCoding, valentyn-bulakh, Kostiantyn-Miniailo
          minimum-approvals: 1
          issue-title: "Deploying to Sandbox version ${{ needs.build.outputs.image_tag }}"
          issue-body: "Please approve or deny the deployment for Sandbox for version ${{ needs.build.outputs.image_tag }}"
          exclude-workflow-initiator-as-approver: false
          additional-approved-words: ''
          additional-denied-words: ''          
          
  deploy:
    runs-on: ["elmeas", "Linux"] 
    needs: [build, check-approvals]
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Preperation
      uses: ./.github/actions/prepare
      with:
        gke_cluster: sandbox-cluster
        gcp_project: elmeas-sandbox
        gcp_region: europe-west3
        google_cred: ${{ secrets.GOOGLE_CREDENTIALS }}
        gcr_domain: ${{ vars.GCR_DOMAIN }}
    
    - name: Deploy
      uses: ./.github/actions/deploy
      with:
        name: ehrbase
        namespace: ehrbase
        environment: sandbox
        image_tag: ${{ needs.build.outputs.image_tag }}
